"""add index on log date

Revision ID: 2e1eb0033eb3
Revises: 60c1efa5deda
Create Date: 2026-09-11 06:03:09.585259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e1eb0033eb3'
down_revision: Union[str, Sequence[str], None] = '60c1efa5deda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_logs_date'), 'logs', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_date'), table_name='logs')
    # ### end Alembic commands ###
