"""empty message

Revision ID: 5b75c2fe056d
Revises: 5aa1bd5716ba
Create Date: 2026-09-08 05:31:10.428759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b75c2fe056d'
down_revision: Union[str, Sequence[str], None] = '5aa1bd5716ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
                postgresql_using="date::date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logs', 'date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
