"""add UserProfile

Revision ID: 6f9c7c6c0834
Revises: d2b0fb89222c
Create Date: 2026-10-05 06:31:21.933175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9c7c6c0834'
down_revision: Union[str, Sequence[str], None] = 'd2b0fb89222c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userprofiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Enum('male', 'female', name='sex'), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('activity_level', sa.Enum('sedentary', 'light', 'moderate', 'high', 'very_high', name='activity_level'), nullable=False),
    sa.Column('goal', sa.Enum('reduction', 'maintenance', 'gain', name='goal'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userprofiles')
    # ### end Alembic commands ###
