"""add product type

Revision ID: 7250c59396a1
Revises: 2e1eb0033eb3
Create Date: 2026-09-14 06:08:18.345849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7250c59396a1'
down_revision: Union[str, Sequence[str], None] = '2e1eb0033eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('type', sa.Enum('ingredient', 'product', 'dish', name='product_type'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('products', 'type')
    sa.Enum(name='product_type').drop(op.get_bind(), checkfirst=True)
