"""add product ownership

Revision ID: 7a4785f3342e
Revises: 808265e62d43
Create Date: 2026-09-29 06:19:19.569401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a4785f3342e'
down_revision: Union[str, Sequence[str], None] = '808265e62d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('is_global', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.drop_index(op.f('uq_active_product_name'), table_name='products', postgresql_where='(active IS TRUE)')
    op.create_foreign_key(None, 'products', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_index(op.f('uq_active_product_name'), 'products', ['name'], unique=True, postgresql_where='(active IS TRUE)')
    op.drop_column('products', 'is_global')
    op.drop_column('products', 'owner_id')
    # ### end Alembic commands ###
