"""baseline

Revision ID: 7f4cd8f67358
Revises: 
Create Date: 2026-10-09 06:51:13.106594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f4cd8f67358'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('ingredient', 'product', 'dish', name='product_type'), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.CheckConstraint('calories >= 0', name='Pcalories_nonnegative'),
    sa.CheckConstraint('carbs >= 0', name='Pcarbs_nonnegative'),
    sa.CheckConstraint('fat >= 0', name='Pfat_nonnegative'),
    sa.CheckConstraint('protein >= 0', name='Pprotein_nonnegative'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_active_global_product_name', 'products', ['name'], unique=True, postgresql_where=sa.text('active IS TRUE AND is_global IS TRUE'))
    op.create_index('uq_active_product_name', 'products', ['owner_id', 'name'], unique=True, postgresql_where=sa.text('active IS TRUE'))
    op.create_table('userprofiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sex', sa.Enum('male', 'female', name='sex'), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('activity_level', sa.Enum('sedentary', 'light', 'moderate', 'high', 'very_high', name='activity_level'), nullable=False),
    sa.Column('goal', sa.Enum('loss_0_1', 'loss_0_2', 'loss_0_3', 'maintenance', 'gain_0_1', 'gain_0_2', 'gain_0_3', name='goal_rate'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.Enum('ingredient', 'product', 'dish', name='product_type'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.CheckConstraint('calories >= 0', name='Lcalories_nonnegative'),
    sa.CheckConstraint('carbs >= 0', name='Lcarbs_nonnegative'),
    sa.CheckConstraint('fat >= 0', name='Lfat_nonnegative'),
    sa.CheckConstraint('protein >= 0', name='Lprotein_nonnegative'),
    sa.CheckConstraint('weight > 0', name='Lweight_higher_than_zero'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_date'), 'logs', ['date'], unique=False)
    op.create_table('product_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_product_id', sa.Integer(), nullable=False),
    sa.Column('component_product_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.CheckConstraint('weight > 0', name='PCweight_higher_than_zero'),
    sa.ForeignKeyConstraint(['component_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['parent_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_components')
    op.drop_index(op.f('ix_logs_date'), table_name='logs')
    op.drop_table('logs')
    op.drop_table('userprofiles')
    op.drop_index('uq_active_product_name', table_name='products', postgresql_where=sa.text('active IS TRUE'))
    op.drop_index('uq_active_global_product_name', table_name='products', postgresql_where=sa.text('active IS TRUE AND is_global IS TRUE'))
    op.drop_table('products')
    op.drop_table('users')
    # ### end Alembic commands ###
