"""add user-logs relationship

Revision ID: 808265e62d43
Revises: 88f67420d600
Create Date: 2026-09-25 04:37:51.999240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '808265e62d43'
down_revision: Union[str, Sequence[str], None] = '88f67420d600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_logs_user_id_users', 'logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_logs_user_id_users', 'logs', type_='foreignkey')
    op.drop_column('logs', 'user_id')
    # ### end Alembic commands ###
