"""empty message

Revision ID: 8953fdba5937
Revises: 5b75c2fe056d
Create Date: 2026-09-09 05:04:51.346200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8953fdba5937'
down_revision: Union[str, Sequence[str], None] = '5b75c2fe056d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_products_name', 'products', ['name'])
    op.create_check_constraint('calories_nonnegative', 'products', 'calories >= 0')
    op.create_check_constraint('carbs_nonnegative', 'products', 'carbs >= 0')
    op.create_check_constraint('fat_nonnegative', 'products', 'fat >= 0')
    op.create_check_constraint('protein_nonnegative', 'products', 'protein >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('protein_nonnegative', 'products', type_='check')
    op.drop_constraint('fat_nonnegative', 'products', type_='check')
    op.drop_constraint('carbs_nonnegative', 'products', type_='check')
    op.drop_constraint('calories_nonnegative', 'products', type_='check')
    op.drop_constraint('uq_products_name', 'products', type_='unique')
    # ### end Alembic commands ###
