"""empty message

Revision ID: 9f78c2b9c49d
Revises: 66bd70d14ac7
Create Date: 2026-09-09 05:28:39.764448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f78c2b9c49d'
down_revision: Union[str, Sequence[str], None] = '66bd70d14ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('Lcalories_nonnegative', 'logs', 'calories >= 0')
    op.create_check_constraint('Lcarbs_nonnegative', 'logs', 'carbs >= 0')
    op.create_check_constraint('Lfat_nonnegative', 'logs', 'fat >= 0')
    op.create_check_constraint('Lprotein_nonnegative', 'logs', 'protein >= 0')
    op.create_check_constraint('Lweight_higher_than_zero', 'logs', 'weight > 0')
    op.create_index('uq_active_product_name', 'products', ['name'], unique=True, postgresql_where=sa.text('active IS TRUE'))
    op.drop_constraint(op.f('calories_nonnegative'), 'products', type_='check')
    op.drop_constraint(op.f('carbs_nonnegative'), 'products', type_='check')
    op.drop_constraint(op.f('fat_nonnegative'), 'products', type_='check')
    op.drop_constraint(op.f('protein_nonnegative'), 'products', type_='check')
    op.create_check_constraint('Pcalories_nonnegative', 'products', 'calories >= 0')
    op.create_check_constraint('Pcarbs_nonnegative', 'products', 'carbs >= 0')
    op.create_check_constraint('Pfat_nonnegative', 'products', 'fat >= 0')
    op.create_check_constraint('Pprotein_nonnegative', 'products', 'protein >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Pprotein_nonnegative', 'products', type_='check')
    op.drop_constraint('Pfat_nonnegative', 'products', type_='check')
    op.drop_constraint('Pcarbs_nonnegative', 'products', type_='check')
    op.drop_constraint('Pcalories_nonnegative', 'products', type_='check')
    op.create_check_constraint(op.f('protein_nonnegative'), 'products', 'protein >= 0::double precision')
    op.create_check_constraint(op.f('fat_nonnegative'), 'products', 'fat >= 0::double precision')
    op.create_check_constraint(op.f('carbs_nonnegative'), 'products', 'carbs >= 0::double precision')
    op.create_check_constraint(op.f('calories_nonnegative'), 'products', 'calories >= 0::double precision')
    op.drop_index('uq_active_product_name', table_name='products', postgresql_where=sa.text('active IS TRUE'))
    op.drop_constraint('Lweight_higher_than_zero', 'logs', type_='check')
    op.drop_constraint('Lprotein_nonnegative', 'logs', type_='check')
    op.drop_constraint('Lfat_nonnegative', 'logs', type_='check')
    op.drop_constraint('Lcarbs_nonnegative', 'logs', type_='check')
    op.drop_constraint('Lcalories_nonnegative', 'logs', type_='check')
    # ### end Alembic commands ###
