"""add product components

Revision ID: cbcf23d38b8e
Revises: a87a195bcb16
Create Date: 2026-09-15 06:36:35.139068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbcf23d38b8e'
down_revision: Union[str, Sequence[str], None] = 'a87a195bcb16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_product_id', sa.Integer(), nullable=False),
    sa.Column('component_product_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.CheckConstraint('weight > 0', name='PCweight_higher_than_zero'),
    sa.ForeignKeyConstraint(['component_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['parent_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_components')
    # ### end Alembic commands ###
