"""finalize product ownership

Revision ID: d2b0fb89222c
Revises: 7a4785f3342e
Create Date: 2026-09-29 06:26:17.315121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2b0fb89222c'
down_revision: Union[str, Sequence[str], None] = '7a4785f3342e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('uq_active_global_product_name', 'products', ['name'], unique=True, postgresql_where=sa.text('active IS TRUE AND is_global IS TRUE'))
    op.create_index('uq_active_product_name', 'products', ['owner_id', 'name'], unique=True, postgresql_where=sa.text('active IS TRUE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_product_name', table_name='products', postgresql_where=sa.text('active IS TRUE'))
    op.drop_index('uq_active_global_product_name', table_name='products', postgresql_where=sa.text('active IS TRUE AND is_global IS TRUE'))
    op.alter_column('products', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
